export const userRegistrationFields = [
  {
    name: 'userId',
    label: 'User ID',
    type: 'text',
    required: true,
    maxLength: 12,
    placeholder: '12-digit login ID',
    hint: 'First 4 digits identify the client (tenant)',
    colSpan: 2,
  },
  {
    name: 'userName',
    label: 'Username',
    type: 'text',
    required: true,
    placeholder: 'Display name',
  },
  {
    name: 'userMail',
    label: 'Email',
    type: 'email',
    required: true,
    maxLength: 150,
    placeholder: 'user@company.com',
  },
  {
    name: 'mobileNo',
    label: 'Mobile Number',
    type: 'tel',
    required: true,
    maxLength: 10,
    minLength: 10,
    placeholder: '10-digit number',
  },
  {
    name: 'password',
    label: 'Password',
    type: 'password',
    required: true,
    placeholder: 'Set login password',
  },
  {
    name: 'userType',
    label: 'User Type',
    type: 'select',
    required: true,
    options: [
      { value: 'ADMIN', label: 'Admin' },
      { value: 'EMPLOYEE', label: 'Employee' },
      { value: 'USER', label: 'User' },
    ],
  },
  {
    name: 'status',
    label: 'Status',
    type: 'select',
    required: true,
    defaultValue: 'ACTIVE',
    options: [
      { value: 'ACTIVE', label: 'Active' },
      { value: 'INACTIVE', label: 'Inactive' },
    ],
  },
];

export const employeeRegistrationFields = [
  {
    name: 'employeeCode',
    label: 'Employee Code',
    type: 'text',
    required: true,
    maxLength: 20,
    placeholder: 'Unique employee code',
  },
  {
    name: 'loginId',
    label: 'Login ID',
    type: 'text',
    maxLength: 12,
    placeholder: 'Portal login ID (optional)',
    hint: 'Links to user_login if employee has portal access',
  },
  {
    name: 'firstName',
    label: 'First Name',
    type: 'text',
    required: true,
    placeholder: 'First name',
  },
  {
    name: 'lastName',
    label: 'Last Name',
    type: 'text',
    placeholder: 'Last name',
  },
  {
    name: 'email',
    label: 'Email',
    type: 'email',
    required: true,
    maxLength: 150,
    placeholder: 'employee@company.com',
  },
  {
    name: 'mobileNo',
    label: 'Mobile Number',
    type: 'tel',
    required: true,
    maxLength: 10,
    minLength: 10,
    placeholder: '10-digit number',
  },
  {
    name: 'dateOfBirth',
    label: 'Date of Birth',
    type: 'date',
  },
  {
    name: 'dateOfJoining',
    label: 'Date of Joining',
    type: 'date',
    required: true,
  },
  {
    name: 'department',
    label: 'Department',
    type: 'text',
    placeholder: 'e.g. Engineering',
  },
  {
    name: 'designation',
    label: 'Designation',
    type: 'text',
    placeholder: 'e.g. Software Engineer',
  },
  {
    name: 'reportingManagerId',
    label: 'Reporting Manager ID',
    type: 'number',
    placeholder: 'Employee ID of manager',
    hint: 'Leave empty for top-level roles',
  },
  {
    name: 'status',
    label: 'Status',
    type: 'select',
    required: true,
    defaultValue: 'ACTIVE',
    options: [
      { value: 'ACTIVE', label: 'Active' },
      { value: 'INACTIVE', label: 'Inactive' },
      { value: 'RESIGNED', label: 'Resigned' },
      { value: 'TERMINATED', label: 'Terminated' },
    ],
  },
];

export const clientRegistrationFields = [
  {
    name: 'clientId',
    label: 'Client ID',
    type: 'text',
    required: true,
    placeholder: 'Unique client identifier',
  },
  {
    name: 'clientName',
    label: 'Client Name',
    type: 'text',
    required: true,
    placeholder: 'Organization name',
  },
  {
    name: 'url',
    label: 'URL',
    type: 'text',
    placeholder: 'https://client.example.com',
    colSpan: 2,
  },
  {
    name: 'username',
    label: 'Username',
    type: 'text',
    placeholder: 'Client portal username',
  },
  {
    name: 'password',
    label: 'Password',
    type: 'password',
    placeholder: 'Client portal password',
  },
  {
    name: 'status',
    label: 'Status',
    type: 'select',
    defaultValue: 'ACTIVE',
    options: [
      { value: 'ACTIVE', label: 'Active' },
      { value: 'INACTIVE', label: 'Inactive' },
    ],
  },
];
